import os

LOG_DIR = './logs'

# Each directory is scanned non-recursively for *.xes and *.xes.gz files.
# Epoch ranges are inclusive. Add another dictionary to add another log set.
TRAINING_LOG_SETS = [
    {
        'name': 'logs',
        'directory': LOG_DIR,
        'epochs': (1, 100),
    },
    {
        'name': 'logs_out',
        'directory': os.path.join(LOG_DIR, 'out'),
        'epochs': (10, 100),
    },
]

CONFIG = {
    'training_log_sets': TRAINING_LOG_SETS,
    'log_paths': {
        'testing': {
            'D_unseen': os.path.join(LOG_DIR, '00013_clos2rep.xes.gz'),
        },
    },
'moe_settings':{
'num_experts':4
},
'embedding_strategy':'learned',
'pretrained_settings':{
'sbert_model':'all-mpnet-base-v2',
'embedding_dim':768 ,
},
'learned_settings':{
'char_embedding_dim':64 ,
'char_cnn_output_dim':128 ,
},
'd_model':256 ,
'n_heads':8 ,
'n_layers':6 ,
'dropout':0.15 ,
'num_numerical_features':3 ,
'num_shots_range':(1 ,20 ),
'num_queries':10 ,
'num_shots_test':[1 ,5 ,10 ,20 ],
'lr':1e-4 ,
'weight_decay':0.01 ,
'epochs':60 ,
'episodes_per_epoch':300 ,
'episodic_label_shuffle':'yes', #no, yes, mixed
'training_strategy':'retrieval', #episodic, retrieval, mixed
'classification_label_smoothing':0.05,
'classification_objective':{
'profile':'equilibrated',
'weights':{},
},
'classification_separation_weight':0.0,
'classification_separation_temperature':0.10,
'classification_separation_margin':0.15,
'proto_head_warmup_epochs':3 ,
'proto_head_lr_mult_after_warmup':0.1 ,
'retrieval_train_k':32 ,
'retrieval_train_batch_size':128 ,
'retrieval_min_per_class':2 ,
'retrieval_train_max_classes':32 ,
'retrieval_cls_pos_k':2 ,
'retrieval_pos_use_nearest':True ,
'retrieval_neg_pool_factor':8 ,
'retrieval_neg_random_frac':0.35 ,
'retrieval_contrastive_weight':0.25 ,
'retrieval_contrastive_temp':0.10 ,
'retrieval_regression_pos_k':2 ,
'retrieval_knn_aux_weight':0.1 ,
'retrieval_var_weight':0.03 ,
'retrieval_cov_weight':0.03 ,
'retrieval_reg_ramp_epochs':10 ,
'retrieval_contrastive_ramp':True ,
'retrieval_k_start':12 ,
'retrieval_k_end':32 ,
'retrieval_k_ramp_epochs':8 ,
'retrieval_neg_random_frac_start':0.60 ,
'retrieval_neg_random_frac_end':0.15 ,
'retrieval_pos_nearest_epochs':2 ,
'test_mode':'retrieval_augmented',
'test_retrieval_k':[1 ,5 ,10 ,20 ,50 ,100 ,200 ],
'test_retrieval_candidate_percentages':[0.5 ,1 ,3 ,5 ,10 ,20 ,50 ,100 ],
'test_retrieval_eval_scope':'experts' , # experts, model
'test_retrieval_prediction_mode':'proto_head' , # proto_head, foundation_knn
'test_retrieval_report_confidence_buckets':False , # only for proto_head
'test_retrieval_first_expert_only':False ,
'num_test_episodes':200 ,
'num_cases_for_testing':500 ,
'seed':42,
'training_enabled':True,
'gradient_clip_norm':1.0,
'training_lr_multipliers':{},
'training_diagnostics':{
'enabled':False,
'step_interval':25,
'loss_gradient_interval':0,
'validation_fraction':0.10,
'validation_steps_per_pool':1,
'validation_seed_offset':100000,
'overfitting_patience':3,
'overfitting_relative_tolerance':0.02,
},
'fmv3_head':{
'classification_mode':'legacy_soft_knn', # legacy_soft_knn, local, global, global_local, coverage_fallback
'local_temperature':0.2,
'global_temperature':0.2,
'learn_temperature':False,
'local_centering':False,
'global_centering':False,
'coverage_fallback_margin':0.5,
'inference_temperature':1.0,
'fallback_inference_temperature':1.0,
'count_normalization':'fixed', # fixed, learned
'count_normalization_gamma':0.0,
'prior_mode':'none', # none, uniform/balanced, natural
'prior_strength':0.0,
'prior_smoothing':1.0,
'shrinkage_mode':'none', # none, fixed, learned
'shrinkage_kappa':2.0,
'gate_mode':'fixed', # fixed, dynamic
'local_gate':0.5,
'enable_abstention':False,
'abstain_label':-101,
'abstain_bias':0.0,
'abstain_slope':2.0,
'regression_mode':'sqrt_knn', # sqrt_knn, raw_hours_knn, learned_transform_ensemble
'regression_num_transforms':8,
'regression_transform_aggregation':'learned', # learned, mean
'regression_power_min':0.05,
'regression_power_max':1.5,
'regression_transform_scale_min_hours':1.0,
'regression_transform_scale_max_hours':10000.0,
'regression_scale_augmentation':True,
'regression_scale_augmentation_min':0.02,
'regression_scale_augmentation_max':50.0,
'regression_time_input_transforms':False,
'regression_time_replace_legacy':False,
'regression_input_scale_min_hours':0.0002777777777777778,
'regression_input_scale_max_hours':10000.0,
'regression_input_residual_logit':-2.0,
'temporal_input_transforms':False,
'temporal_replace_legacy_inputs':False,
'temporal_start_num_transforms':4,
'temporal_start_power_min':0.05,
'temporal_start_power_max':1.5,
'temporal_start_scale_min_hours':1.0 /60.0,
'temporal_start_scale_max_hours':10000.0,
'temporal_start_residual_logit':-3.0,
'temporal_previous_num_transforms':4,
'temporal_previous_power_min':0.05,
'temporal_previous_power_max':1.5,
'temporal_previous_scale_min_hours':1.0 /3600.0,
'temporal_previous_scale_max_hours':1000.0,
'temporal_previous_residual_logit':-3.0,
'state_aware_prefix_attention':False,
'prefix_attention_hidden_dim':128,
'prefix_attention_dropout':0.15,
'prefix_attention_gate_logit':-3.0,
'prefix_attention_initial_recency':0.25,
'classification_embedding_adapter_enabled':False,
'classification_embedding_adapter_hidden_dim':64,
'classification_embedding_adapter_dropout':0.0,
'regression_embedding_adapter_enabled':False,
'regression_embedding_adapter_hidden_dim':64,
'regression_embedding_adapter_dropout':0.0,
'example_selector_hidden_dim':16,
'classification_example_selector_enabled':False,
'classification_example_selector_hidden_dim':16,
'classification_example_selector_max_log_weight':2.0,
'classification_example_selector_strength':1.0,
'regression_example_selector_enabled':False,
'regression_example_selector_hidden_dim':16,
'regression_example_selector_max_log_weight':2.0,
'regression_example_selector_strength':1.0,
'regression_mae_weight':0.5,
'regression_rmse_weight':0.5,
'regression_r2_weight':0.0,
'regression_objective_profile':'equilibrated',
'regression_metric_weights':{},
'regression_r2_variance_floor':1e-4,
'regression_huber_weight':0.15,
'regression_huber_delta':1.0,
'regression_log_rmse_weight':0.15,
'regression_relative_mae_weight':0.05,
'regression_bias_weight':0.05,
'regression_median_ae_weight':0.0,
'regression_quantile_weight':0.0,
'regression_quantile_level':0.5,
'regression_loss_scale_power':1.0,
'regression_loss_reference_hours':100.0,
'regression_gate_aux_weight':0.0,
'regression_gate_target_temperature':0.1,
'classification_expert_confidence_enabled':False,
'regression_expert_confidence_enabled':False,
'expert_confidence_hidden_dim':16,
'classification_expert_confidence_loss_weight':0.0,
'regression_expert_confidence_loss_weight':0.0,
'expert_routing_confidence_enabled':False,
'expert_routing_architecture':'mlp', # task_bias, linear, mlp
'expert_routing_hidden_dim':32,
'expert_routing_dropout':0.0,
'expert_routing_confidence_loss_weight':0.0,
'expert_active_fraction':0.5,
'expert_routing_temperature':1.0,
},
'fmv3_training':{
'episode_mix':{'balanced':1.0},
'long_tail_power':1.5,
'random_shot_min':1,
'random_shot_max':20,
'missing_local_fraction':1.0,
'missing_pool_fraction':1.0,
},
'fmv3_evaluation':{
'case_budgets':[1,2,4,8,16,32,64,128],
'support_scenarios':['natural','class_aware'],
'repetitions':5,
'test_case_fraction':0.3,
'max_test_cases':50,
'max_query_prefixes':1000,
'embedding_batch_size':128,
'include_full_budget':True,
'include_full_budget_max_cases':1000,
'retrieval_k':[5,20,50],
'bootstrap_repetitions':200,
'prior_modes':['balanced','natural'],
'prior_strengths':[1.0],
'retrieval_modes':['configured'],
'dynamic_retrieval_max_k':200,
'dynamic_retrieval_entropy_threshold':0.65,
'threshold_fraction':0.9,
'structured_max_order':3,
'structured_smoothing':0.5,
'structured_weight':0.75,
'structured_tau':0.5,
'structured_low_support_threshold':0,
'structured_low_support_weight':None,
'structured_low_support_tau':None,
'classification_output_temperature':1.0,
'virtual_expert_replicates':1,
'virtual_expert_support_fraction':1.0,
'virtual_expert_min_support_prefixes':1,
'virtual_expert_include_full_support':True,
'virtual_expert_preserve_labels':True,
'virtual_expert_full_support_weight':1.0,
'virtual_expert_subbag_weight':1.0,
'virtual_expert_seed':42,
'regression_branch_diagnostics':False,
'regression_support_calibration':False,
'regression_calibration_max_prefixes':512,
'regression_calibration_temperature':20.0,
'regression_calibration_mae_weight':0.5,
'regression_calibration_rmse_weight':0.5,
'regression_calibration_exclude_same_case':False,
'regression_calibration_mix':1.0,
'regression_calibration_mix_by_budget':{},
'regression_expert_confidence_temperature':1.0,
'regression_interval_std_multiplier':1.645,
'expert_aggregation_diagnostics':False,
'evaluation_profiles':[
{'name':'main','retrieval_modes':['configured'],'prior_modes':['balanced','natural'],'prior_strengths':[1.0],'retrieval_k':[5,20,50]},
],
},
}
